# Generated by Django 5.0.6 on 2024-06-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fypapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='is_adopted',
        ),
        migrations.AddField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10),
        ),
    ]
