# Generated by Django 5.0.6 on 2024-07-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fypapp', '0002_remove_pet_description_remove_pet_is_adopted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adopters',
            fields=[
                ('adopterid', models.AutoField(primary_key=True, serialize=False)),
                ('adopteremail', models.EmailField(max_length=254, unique=True)),
                ('adopterFirstName', models.CharField(default='John', max_length=100)),
                ('adopterLastName', models.CharField(default='Doe', max_length=100)),
            ],
        ),
    ]
