# Generated by Django 5.0.6 on 2024-07-24 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fypapp', '0003_adopters'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adopters',
            new_name='Adopter',
        ),
    ]
