# Generated by Django 5.0.6 on 2024-07-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fypapp', '0004_rename_adopters_adopter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('shelterid', models.AutoField(primary_key=True, serialize=False)),
                ('sheltername', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contactnumber', models.CharField(max_length=15)),
            ],
        ),
    ]
