# Generated by Django 5.0.6 on 2024-07-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fypapp', '0005_shelter'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$OQ1IYZIK57XhyxiLabctb2$0o/BvoKnIVzrBO0C6q8gI03Dv6z5JZIdiZOJ/SSKl6g=', max_length=128),
        ),
    ]
