# Generated by Django 5.0.6 on 2024-08-01 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fypapp', '0006_shelter_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelter',
            name='password',
        ),
    ]
