# Generated by Django 5.0.6 on 2024-08-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fypapp', '0008_appuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='availability',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='image',
            field=models.ImageField(null=True, upload_to='pet_images/'),
        ),
        migrations.AddField(
            model_name='pet',
            name='size',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
