# Generated by Django 5.0.6 on 2024-08-08 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fypapp', '0009_pet_availability_pet_color_pet_description_pet_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='availability',
        ),
    ]
