# Generated by Django 5.0.6 on 2024-08-11 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fypapp', '0010_remove_pet_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='title',
        ),
    ]
