# Generated by Django 5.0.6 on 2024-08-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fypapp', '0011_remove_pet_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='likes',
            field=models.TextField(null=True),
        ),
    ]
