# Generated by Django 5.0.6 on 2024-08-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fypapp', '0012_pet_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('breed', models.CharField(max_length=100, null=True)),
                ('age', models.PositiveIntegerField(null=True)),
                ('size', models.CharField(max_length=50, null=True)),
                ('color', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(null=True)),
                ('likes', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='pet_images/')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
            ],
        ),
    ]
