# Generated by Django 5.0.6 on 2024-08-21 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fypapp', '0016_shelter_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelter',
            name='user',
        ),
    ]
