# Generated by Django 5.0.6 on 2024-08-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fypapp', '0017_remove_shelter_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='id',
        ),
        migrations.AddField(
            model_name='event',
            name='eventid',
            field=models.AutoField(default='1', primary_key=True, serialize=False),
        ),
    ]
