# Generated by Django 5.0.6 on 2024-08-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fypapp', '0018_remove_event_id_event_eventid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('meetingid', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=255)),
                ('phonenumber', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('about', models.TextField()),
                ('experience', models.CharField(max_length=255)),
                ('meeting_time', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='eventid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
