# Generated by Django 5.0.6 on 2024-08-23 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fypapp', '0019_meeting_alter_event_eventid'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='pet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fypapp.pet'),
        ),
    ]
