# Generated by Django 5.0.6 on 2024-08-24 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fypapp', '0020_meeting_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='shelter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets', to='fypapp.shelter'),
        ),
        migrations.AddField(
            model_name='pet2',
            name='shelter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets2', to='fypapp.shelter'),
        ),
    ]
